# Generated by Django 5.0.14 on 2026-02-19 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Budowa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=200, verbose_name="Nazwa")),
                (
                    "miejsce",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Miejsce"
                    ),
                ),
                (
                    "adres",
                    models.CharField(blank=True, max_length=300, verbose_name="Adres"),
                ),
            ],
            options={
                "verbose_name": "Budowa",
                "verbose_name_plural": "Budowy",
                "ordering": ["nazwa"],
            },
        ),
        migrations.CreateModel(
            name="Mieszkanie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=200, verbose_name="Nazwa")),
                ("adres", models.CharField(max_length=300, verbose_name="Adres")),
                (
                    "miasto",
                    models.CharField(blank=True, max_length=100, verbose_name="Miasto"),
                ),
                (
                    "pojemnosc",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Pojemność (osób)"
                    ),
                ),
                ("uwagi", models.TextField(blank=True, verbose_name="Uwagi")),
            ],
            options={
                "verbose_name": "Mieszkanie",
                "verbose_name_plural": "Mieszkania",
                "ordering": ["nazwa"],
            },
        ),
        migrations.CreateModel(
            name="Pojazd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marka", models.CharField(max_length=100, verbose_name="Marka")),
                (
                    "model_pojazdu",
                    models.CharField(max_length=100, verbose_name="Model"),
                ),
                (
                    "nr_rejestracyjny",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Nr rejestracyjny"
                    ),
                ),
                (
                    "przebieg_km",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Przebieg (km)"
                    ),
                ),
                (
                    "rok_produkcji",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Rok produkcji"
                    ),
                ),
                (
                    "data_przegladu",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data przeglądu"
                    ),
                ),
                (
                    "data_ubezpieczenia",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data ubezpieczenia"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pojazd",
                "verbose_name_plural": "Pojazdy",
                "ordering": ["nr_rejestracyjny"],
            },
        ),
        migrations.CreateModel(
            name="Pracownik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imie", models.CharField(max_length=100, verbose_name="Imię")),
                ("nazwisko", models.CharField(max_length=100, verbose_name="Nazwisko")),
                (
                    "pesel",
                    models.CharField(max_length=11, unique=True, verbose_name="PESEL"),
                ),
                (
                    "ulica_nr",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ulica i nr"
                    ),
                ),
                (
                    "kod_pocztowy",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Kod pocztowy"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "dowod_osobisty",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Dowód osobisty"
                    ),
                ),
                (
                    "telefon",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "data_utworzenia",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pracownik",
                "verbose_name_plural": "Pracownicy",
                "ordering": ["nazwisko", "imie"],
            },
        ),
        migrations.CreateModel(
            name="PracownikBudowa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_od",
                    models.DateField(blank=True, null=True, verbose_name="Data od"),
                ),
                (
                    "data_do",
                    models.DateField(blank=True, null=True, verbose_name="Data do"),
                ),
                (
                    "budowa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="przypisani_pracownicy",
                        to="kadry.budowa",
                        verbose_name="Budowa",
                    ),
                ),
                (
                    "pracownik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="przypisania_budowy",
                        to="kadry.pracownik",
                        verbose_name="Pracownik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Przypisanie do budowy",
                "verbose_name_plural": "Przypisania do budów",
                "ordering": ["-data_od"],
            },
        ),
        migrations.CreateModel(
            name="ZdarzenieFloty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("serwis", "Serwis"),
                            ("naprawa", "Naprawa"),
                            ("tankowanie", "Tankowanie"),
                            ("wypadek", "Wypadek"),
                            ("mandaty", "Mandaty"),
                            ("przeglad", "Przegląd techniczny"),
                            ("ubezpieczenie", "Ubezpieczenie"),
                            ("inne", "Inne"),
                        ],
                        default="inne",
                        max_length=30,
                        verbose_name="Typ",
                    ),
                ),
                ("opis", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "przebieg_km",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Przebieg (km)"
                    ),
                ),
                (
                    "koszt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Koszt (PLN)",
                    ),
                ),
                (
                    "pojazd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zdarzenia",
                        to="kadry.pojazd",
                        verbose_name="Pojazd",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zdarzenie floty",
                "verbose_name_plural": "Zdarzenia floty",
                "ordering": ["-data"],
            },
        ),
    ]
