# Generated by Django 5.0.14 on 2026-03-08 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kadry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zalacznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('plik', models.FileField(upload_to='zalaczniki/%Y/%m/', verbose_name='Plik')),
                ('typ_dokumentu', models.CharField(choices=[('dowod_przod', 'Dowód osobisty - przód'), ('dowod_tyl', 'Dowód osobisty - tył'), ('wzor_podpisu', 'Wzór podpisu'), ('skan', 'Skan dokumentu'), ('zdjecie', 'Zdjęcie'), ('inne', 'Inne')], default='inne', max_length=50, verbose_name='Typ załącznika')),
                ('opis', models.CharField(blank=True, max_length=255, verbose_name='Opcjonalny opis')),
                ('data_dodania', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Załącznik',
                'verbose_name_plural': 'Załączniki',
                'ordering': ['-data_dodania'],
            },
        ),
    ]
