# Generated by Django 5.0.14 on 2026-04-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadry', '0002_zalacznik'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='a1_do',
            field=models.DateField(blank=True, null=True, verbose_name='Aktualna A1 (do)'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='a1_od',
            field=models.DateField(blank=True, null=True, verbose_name='Aktualna A1 (od)'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='badania_do',
            field=models.DateField(blank=True, null=True, verbose_name='Badania (do)'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='badania_od',
            field=models.DateField(blank=True, null=True, verbose_name='Badania (od)'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='ekuz_do',
            field=models.DateField(blank=True, null=True, verbose_name='EKUZ (do)'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='ekuz_od',
            field=models.DateField(blank=True, null=True, verbose_name='EKUZ (od)'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='status',
            field=models.CharField(choices=[('nieokreslona', 'Umowa nieokreślona'), ('okreslona', 'Umowa określona'), ('probna', 'Umowa próbna'), ('rezygnacja', 'Rezygnacja / Zwolniony')], default='nieokreslona', max_length=20, verbose_name='Status pracownika'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='umowa_okreslona_do',
            field=models.DateField(blank=True, null=True, verbose_name='Umowa określona (do)'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='umowa_okreslona_od',
            field=models.DateField(blank=True, null=True, verbose_name='Umowa określona (od)'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='umowa_probna_do',
            field=models.DateField(blank=True, null=True, verbose_name='Umowa próbna (do)'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='umowa_probna_od',
            field=models.DateField(blank=True, null=True, verbose_name='Umowa próbna (od)'),
        ),
    ]
