# Generated by Django 5.0.14 on 2026-04-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadry', '0003_pracownik_a1_do_pracownik_a1_od_pracownik_badania_do_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='opis',
            field=models.TextField(blank=True, verbose_name='Dodatkowy opis'),
        ),
    ]
