# Generated by Django 5.0.14 on 2026-04-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadry', '0004_pracownik_opis'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='miejscowosc',
            field=models.CharField(blank=True, max_length=150, verbose_name='Miejscowość'),
        ),
    ]
