# Generated by Django 5.0.14 on 2026-04-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadry', '0005_pracownik_miejscowosc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownikbudowa',
            name='godziny',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Liczba godzin'),
        ),
    ]
