# Generated by Django 5.0.14 on 2026-08-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kadry", "0006_pracownikbudowa_godziny"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faktura",
            fields=[
                (
                    "ksef_number",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Numer KSeF",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(max_length=256, verbose_name="Numer faktury"),
                ),
                (
                    "subject_role",
                    models.CharField(
                        choices=[("buyer", "Zakup"), ("seller", "Sprzedaż")],
                        max_length=10,
                        verbose_name="Rodzaj",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(null=True, verbose_name="Data wystawienia"),
                ),
                (
                    "invoicing_date",
                    models.DateTimeField(null=True, verbose_name="Przyjęcie w KSeF"),
                ),
                (
                    "acquisition_date",
                    models.DateTimeField(null=True, verbose_name="Data otrzymania"),
                ),
                (
                    "permanent_storage_date",
                    models.DateTimeField(null=True, verbose_name="Trwały zapis w KSeF"),
                ),
                (
                    "seller_nip",
                    models.CharField(
                        max_length=20, null=True, verbose_name="NIP sprzedawcy"
                    ),
                ),
                (
                    "seller_name",
                    models.CharField(
                        max_length=512, null=True, verbose_name="Sprzedawca"
                    ),
                ),
                (
                    "buyer_identifier_type",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Typ id. nabywcy"
                    ),
                ),
                (
                    "buyer_identifier_value",
                    models.CharField(
                        max_length=50, null=True, verbose_name="NIP nabywcy"
                    ),
                ),
                (
                    "buyer_name",
                    models.CharField(max_length=512, null=True, verbose_name="Nabywca"),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, null=True, verbose_name="Netto"
                    ),
                ),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Brutto",
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, null=True, verbose_name="VAT"
                    ),
                ),
                (
                    "currency",
                    models.CharField(max_length=8, null=True, verbose_name="Waluta"),
                ),
                (
                    "invoicing_mode",
                    models.CharField(
                        max_length=16, null=True, verbose_name="Tryb wysyłki"
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(max_length=16, null=True, verbose_name="Typ"),
                ),
                (
                    "is_self_invoicing",
                    models.BooleanField(null=True, verbose_name="Samofakturowanie"),
                ),
                (
                    "has_attachment",
                    models.BooleanField(null=True, verbose_name="Ma załącznik"),
                ),
                (
                    "invoice_hash",
                    models.CharField(
                        max_length=128, null=True, verbose_name="Skrót faktury"
                    ),
                ),
                (
                    "hash_of_corrected_invoice",
                    models.CharField(
                        max_length=128,
                        null=True,
                        verbose_name="Skrót faktury korygowanej",
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(null=True, verbose_name="Pobrano"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(null=True, verbose_name="Aktualizacja"),
                ),
            ],
            options={
                "verbose_name": "Faktura",
                "verbose_name_plural": "Faktury",
                "db_table": '"ksef"."invoices"',
                "ordering": ["-issue_date", "invoice_number"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FakturaXml",
            fields=[
                (
                    "ksef_number",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Numer KSeF",
                    ),
                ),
                ("byte_size", models.IntegerField(verbose_name="Rozmiar (B)")),
                (
                    "sha256_base64",
                    models.CharField(max_length=128, null=True, verbose_name="SHA-256"),
                ),
                (
                    "hash_verified",
                    models.BooleanField(null=True, verbose_name="Skrót zgodny"),
                ),
                ("downloaded_at", models.DateTimeField(verbose_name="Pobrano")),
            ],
            options={
                "verbose_name": "Plik XML faktury",
                "verbose_name_plural": "Pliki XML faktur",
                "db_table": '"ksef"."invoice_xml"',
                "managed": False,
            },
        ),
    ]
